name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read

jobs: 
  build-ci-container:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secrets check
        run: |
          echo "Username: $DOCKERHUB_USERNAME"
          echo "Token length: ${#DOCKERHUB_TOKEN}"
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with: 
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f .github/workflows/docker/ubuntu-20.04.Dockerfile -t $DOCKERHUB_USERNAME/umf3-ubuntu-20.04:latest .
      - name: Push Docker image to DockerHub
        run: |
          docker push $DOCKERHUB_USERNAME/umf3-ubuntu-20.04:latest
